export const FETCH_ALL_ARTICLES_SUCCESS = "FETCH_ALL_ARTICLES_SUCCESS";
export const FETCH_ALL_ARTICLES_PENDING = "FETCH_ALL_ARTICLES_PENDING";
export const FETCH_ALL_ARTICLES_ERROR = "FETCH_ALL_ARTICLES_ERROR";
