export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
export const SET_USER_DETAIL = "SET_USER_DETAIL";
export const SET_LOADING = "SET_LOADING";
export const DELETE_USER_DETAIL = "DELETE_USER_DETAIL";
